export const CHANGE_BASE_VALUE = "CHANGE_BASE_VALUE";
export const CHANGE_CATEGORY_ID = "CHANGE_CATEGORY_ID";
export const CHANGE_LEFT_UNIT = "CHANGE_LEFT_UNIT";
export const CHANGE_RIGHT_UNIT = "CHANGE_RIGHT_UNIT";
